name: build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.7.1'
      - name: build
        run: |
          project_dir=$(dirname "$(find . -name settings.gradle -not -path './.git/*' | head -n 1)")
          echo "Building in $project_dir"
          cd "$project_dir"
          gradle build
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: '**/build/libs/*.jar'
